import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import "./globals.css";
import ScrollContext from "../../components/ScrollContext";
import Sidebar from "../../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} overflow-x-hidden`}>
        <ScrollContext>
          <Header />
        </ScrollContext>

        <main className="font-inter pt-28">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
